import type { Employee, Store, Task } from '../types';

export const STORES: Store[] = [
  { id: 'store-1', name: 'Downtown Flagship', code: 'STR-101', city: 'Seattle', state: 'WA' },
  { id: 'store-2', name: 'Westside Galleria', code: 'STR-204', city: 'Bellevue', state: 'WA' },
  { id: 'store-3', name: 'Metro Center Plaza', code: 'STR-305', city: 'Portland', state: 'OR' },
  { id: 'store-4', name: 'Northgate Pavilion', code: 'STR-412', city: 'Spokane', state: 'WA' },
  { id: 'store-5', name: 'South Bay Promenade', code: 'STR-518', city: 'San Jose', state: 'CA' },
];

export const EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@taskflow.internal',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'Store Manager',
    storeId: 'store-1',
    storeName: 'Downtown Flagship',
  },
  {
    id: 'emp-2',
    name: 'Marcus Chen',
    email: 'marcus.chen@taskflow.internal',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Inventory Lead',
    storeId: 'store-1',
    storeName: 'Downtown Flagship',
  },
  {
    id: 'emp-3',
    name: 'Elena Rodriguez',
    email: 'elena.rodriguez@taskflow.internal',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Visual Merchandiser',
    storeId: 'store-2',
    storeName: 'Westside Galleria',
  },
  {
    id: 'emp-4',
    name: 'David Kim',
    email: 'david.kim@taskflow.internal',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Shift Lead',
    storeId: 'store-3',
    storeName: 'Metro Center Plaza',
  },
  {
    id: 'emp-5',
    name: 'Aaliyah Patel',
    email: 'aaliyah.patel@taskflow.internal',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'Compliance Officer',
    storeId: 'store-2',
    storeName: 'Westside Galleria',
  },
  {
    id: 'emp-6',
    name: 'Liam Jackson',
    email: 'liam.jackson@taskflow.internal',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    role: 'Store Associate',
    storeId: 'store-4',
    storeName: 'Northgate Pavilion',
  },
  {
    id: 'emp-7',
    name: 'Olivia Martinez',
    email: 'olivia.m@taskflow.internal',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'Customer Service Lead',
    storeId: 'store-5',
    storeName: 'South Bay Promenade',
  },
];

// Helper to generate dynamic relative ISO dates (YYYY-MM-DD)
const getRelativeDateStr = (dayOffset: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  return d.toISOString().split('T')[0];
};

export const INITIAL_TASKS: Task[] = [
  {
    id: 'TASK-101',
    title: 'Audit Spring Apparel Stock & Barcode Recalibration',
    description: 'Perform physical count on Aisle 4 & 5 apparel items. Verify all RFID tags and scan barcodes for system sync.',
    status: 'In Progress',
    priority: 'High',
    category: 'Inventory',
    assigneeId: 'emp-2',
    assignee: {
      id: 'emp-2',
      name: 'Marcus Chen',
      email: 'marcus.chen@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      role: 'Inventory Lead',
    },
    storeId: 'store-1',
    store: {
      id: 'store-1',
      name: 'Downtown Flagship',
      code: 'STR-101',
      city: 'Seattle',
    },
    dueDate: getRelativeDateStr(1), // Tomorrow
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    tags: ['Inventory', 'Apparel', 'Spring Launch'],
    estimatedHours: 4,
  },
  {
    id: 'TASK-102',
    title: 'Install Front Window Promotional Display',
    description: 'Set up seasonal graphic banners, mannequin outfits, and LED spotlighting according to corporate planogram v2.4.',
    status: 'Completed',
    priority: 'Medium',
    category: 'Visual Merchandising',
    assigneeId: 'emp-3',
    assignee: {
      id: 'emp-3',
      name: 'Elena Rodriguez',
      email: 'elena.rodriguez@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      role: 'Visual Merchandiser',
    },
    storeId: 'store-2',
    store: {
      id: 'store-2',
      name: 'Westside Galleria',
      code: 'STR-204',
      city: 'Bellevue',
    },
    dueDate: getRelativeDateStr(-2), // 2 days ago (completed)
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    tags: ['Merchandising', 'Display', 'Q3 Promo'],
    estimatedHours: 6,
  },
  {
    id: 'TASK-103',
    title: 'Quarterly Fire Extinguisher & Emergency Exit Inspection',
    description: 'Verify gauge pressure on all 14 fire extinguishers. Ensure exit corridors remain unobstructed and emergency battery lights engage.',
    status: 'Overdue',
    priority: 'Urgent',
    category: 'Compliance & Safety',
    assigneeId: 'emp-5',
    assignee: {
      id: 'emp-5',
      name: 'Aaliyah Patel',
      email: 'aaliyah.patel@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      role: 'Compliance Officer',
    },
    storeId: 'store-2',
    store: {
      id: 'store-2',
      name: 'Westside Galleria',
      code: 'STR-204',
      city: 'Bellevue',
    },
    dueDate: getRelativeDateStr(-3), // 3 days ago overdue
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    tags: ['Safety', 'OSHA', 'Mandatory'],
    estimatedHours: 2,
  },
  {
    id: 'TASK-104',
    title: 'POS Terminal 3 Touchscreen & Card Reader Diagnostics',
    description: 'Card chip reader reported intermittent failures during peak hours. Run diagnostic utility and replace NFC sensor if needed.',
    status: 'Pending',
    priority: 'High',
    category: 'Cash & POS Operations',
    assigneeId: 'emp-4',
    assignee: {
      id: 'emp-4',
      name: 'David Kim',
      email: 'david.kim@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      role: 'Shift Lead',
    },
    storeId: 'store-3',
    store: {
      id: 'store-3',
      name: 'Metro Center Plaza',
      code: 'STR-305',
      city: 'Portland',
    },
    dueDate: getRelativeDateStr(0), // Today
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    tags: ['POS', 'Hardware', 'Checkout'],
    estimatedHours: 1.5,
  },
  {
    id: 'TASK-105',
    title: 'Resolve VIP Customer Return Claim #84920',
    description: 'Contact customer regarding damaged luxury handbag return. Coordinate with regional logistics for warranty replacement exchange.',
    status: 'In Progress',
    priority: 'Medium',
    category: 'Customer Support',
    assigneeId: 'emp-7',
    assignee: {
      id: 'emp-7',
      name: 'Olivia Martinez',
      email: 'olivia.m@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      role: 'Customer Service Lead',
    },
    storeId: 'store-5',
    store: {
      id: 'store-5',
      name: 'South Bay Promenade',
      code: 'STR-518',
      city: 'San Jose',
    },
    dueDate: getRelativeDateStr(2), // In 2 days
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    tags: ['VIP', 'Customer Escalation', 'Warranty'],
    estimatedHours: 3,
  },
  {
    id: 'TASK-106',
    title: 'HVAC Air Filter Replacement & Refrigeration Check',
    description: 'Replace rooftop HVAC filters unit 1-4 and verify walk-in beverage refrigerator temperature log meets health standards.',
    status: 'Overdue',
    priority: 'High',
    category: 'Store Maintenance',
    assigneeId: 'emp-6',
    assignee: {
      id: 'emp-6',
      name: 'Liam Jackson',
      email: 'liam.jackson@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      role: 'Store Associate',
    },
    storeId: 'store-4',
    store: {
      id: 'store-4',
      name: 'Northgate Pavilion',
      code: 'STR-412',
      city: 'Spokane',
    },
    dueDate: getRelativeDateStr(-1), // 1 day overdue
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    tags: ['Facilities', 'HVAC', 'Maintenance'],
    estimatedHours: 3,
  },
  {
    id: 'TASK-107',
    title: 'Publish Weekend Shift Roster & Overtime Approvals',
    description: 'Finalize employee schedule for upcoming holiday weekend rush. Balance coverage across registers and floor assistance.',
    status: 'Completed',
    priority: 'Urgent',
    category: 'Staff & Scheduling',
    assigneeId: 'emp-1',
    assignee: {
      id: 'emp-1',
      name: 'Sarah Jenkins',
      email: 'sarah.jenkins@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      role: 'Store Manager',
    },
    storeId: 'store-1',
    store: {
      id: 'store-1',
      name: 'Downtown Flagship',
      code: 'STR-101',
      city: 'Seattle',
    },
    dueDate: getRelativeDateStr(-1),
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    tags: ['Staffing', 'Payroll', 'Schedules'],
    estimatedHours: 2,
  },
  {
    id: 'TASK-108',
    title: 'Restock Footwear Endcap & Reorganize Stockroom Bay 2',
    description: 'Transfer popular running shoe models from backroom to sales floor endcap. Sort returned shoe boxes by size.',
    status: 'Pending',
    priority: 'Low',
    category: 'Inventory',
    assigneeId: 'emp-2',
    assignee: {
      id: 'emp-2',
      name: 'Marcus Chen',
      email: 'marcus.chen@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      role: 'Inventory Lead',
    },
    storeId: 'store-1',
    store: {
      id: 'store-1',
      name: 'Downtown Flagship',
      code: 'STR-101',
      city: 'Seattle',
    },
    dueDate: getRelativeDateStr(4), // in 4 days
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    tags: ['Inventory', 'Footwear', 'Stockroom'],
    estimatedHours: 2.5,
  },
  {
    id: 'TASK-109',
    title: 'Staff Security & Anti-Theft Protocol Briefing',
    description: 'Conduct morning huddle with all associates on recent loss prevention directives and tag verification at checkout.',
    status: 'Pending',
    priority: 'Medium',
    category: 'Compliance & Safety',
    assigneeId: 'emp-1',
    assignee: {
      id: 'emp-1',
      name: 'Sarah Jenkins',
      email: 'sarah.jenkins@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      role: 'Store Manager',
    },
    storeId: 'store-1',
    store: {
      id: 'store-1',
      name: 'Downtown Flagship',
      code: 'STR-101',
      city: 'Seattle',
    },
    dueDate: getRelativeDateStr(3),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ['Loss Prevention', 'Training', 'Security'],
    estimatedHours: 1,
  },
  {
    id: 'TASK-110',
    title: 'Daily Cash Drawer Reconciliation & Safe Deposit Drop',
    description: 'Count registers 1 through 6, balance against POS tape, and securely lock cash deposit in drop safe for courier pickup.',
    status: 'Completed',
    priority: 'Urgent',
    category: 'Cash & POS Operations',
    assigneeId: 'emp-4',
    assignee: {
      id: 'emp-4',
      name: 'David Kim',
      email: 'david.kim@taskflow.internal',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      role: 'Shift Lead',
    },
    storeId: 'store-3',
    store: {
      id: 'store-3',
      name: 'Metro Center Plaza',
      code: 'STR-305',
      city: 'Portland',
    },
    dueDate: getRelativeDateStr(0),
    createdAt: new Date(Date.now() - 10 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    tags: ['Finance', 'POS', 'Closing'],
    estimatedHours: 1,
  },
];
